---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  selector:
    matchLabels:
      app: postgresdb
  replicas: 1
  serviceName: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: {{ .Values.image.database.repository }}:{{ .Values.image.database.tag }}
          imagePullPolicy: {{ .Values.image.database.pullPolicy }}
          {{- with .Values.database.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: postgresdb-disk
              mountPath: /data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: password
            - name: POSTGRES_DB
              value: taxi
            - name: PGDATA
              value: /data/pgdata
      # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresdb-disk
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
