
profile: "local-kube"

image:
  rollDeployment: true
  repository: nytaxi
  pullPolicy: IfNotPresent
  tag: 0.0.3

front:
  port: 8080
  resources:

client:
  enabled: false
  resources:

calculator:
  resources:

back:
  port: 8080
  resources:

redis:
  port: 6379
  resources:

database:
  port: "5432"
  resources:

kafka:
  zookeeper:
    resources:
  broker:
    resources:

ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  host: "front.nytaxi"
  path: /(.*)
  service: "front"
