
profile: "dev"

image:
  rollDeployment: true
  repository: nytaxi
  pullPolicy: Always
  tag: dev

front:
  port: 8080

back:
  port: 8080

redis:
  port: 6379

database:
  port: "5432"

client:
  enabled: true

ingress:
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  host: "nytaxi.orozlyvanov.click"
  path: "/"
  service: "front"
