load:
  threads: 60
  record-limits: 0
  duration: 1m
  throttle: 5000
  create-url: 'https://nytaxi.orozlyvanov.click/api/v1/message'
  get-url: 'https://nytaxi.orozlyvanov.click/api/v1/total?year=2018'
  file-path: '/home/o-rozlyvanov/Downloads/2018_Yellow_Taxi_Trip_Data.csv'
  file-type: LOCAL
  request:
    timeout: 5s
authentication:
  url: 'https://nytaxi.orozlyvanov.click/api/v1/authenticator/login'
  id: "default-client"
  password: ",p_(\"[|rjrbf||x~"
